### ISSUE TITLE
Create Room Layout

### ISSUE THREAD

**Issue by jkim68888** [wjdrk70/CodeHouse#17]
## 작업내용
- create room 모달팝업 컴포넌트 생성 후 레이아웃 작업
- Home 과 JoinPage 에 연결

**Comment by wjdrk70** [comment]
그럼 홈 조인하실때 제가 빨리 지금 회원가입 넘어가는거 해서 홈으로 리다이렉팅 끝내고 create room mock api 연결 작업 해보실래요?

**Comment by jkim68888** [comment]
넵 해볼게요!
